// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.6
// source: treevial.proto

package treevialpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ObjectSyncClient is the client API for ObjectSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObjectSyncClient interface {
	Sync(ctx context.Context, opts ...grpc.CallOption) (ObjectSync_SyncClient, error)
}

type objectSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewObjectSyncClient(cc grpc.ClientConnInterface) ObjectSyncClient {
	return &objectSyncClient{cc}
}

func (c *objectSyncClient) Sync(ctx context.Context, opts ...grpc.CallOption) (ObjectSync_SyncClient, error) {
	stream, err := c.cc.NewStream(ctx, &ObjectSync_ServiceDesc.Streams[0], "/treevial.v1.ObjectSync/Sync", opts...)
	if err != nil {
		return nil, err
	}
	x := &objectSyncSyncClient{stream}
	return x, nil
}

type ObjectSync_SyncClient interface {
	Send(*ClientMsg) error
	Recv() (*ServerMsg, error)
	grpc.ClientStream
}

type objectSyncSyncClient struct {
	grpc.ClientStream
}

func (x *objectSyncSyncClient) Send(m *ClientMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *objectSyncSyncClient) Recv() (*ServerMsg, error) {
	m := new(ServerMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ObjectSyncServer is the server API for ObjectSync service.
// All implementations must embed UnimplementedObjectSyncServer
// for forward compatibility
type ObjectSyncServer interface {
	Sync(ObjectSync_SyncServer) error
	mustEmbedUnimplementedObjectSyncServer()
}

// UnimplementedObjectSyncServer must be embedded to have forward compatible implementations.
type UnimplementedObjectSyncServer struct {
}

func (UnimplementedObjectSyncServer) Sync(ObjectSync_SyncServer) error {
	return status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedObjectSyncServer) mustEmbedUnimplementedObjectSyncServer() {}

// UnsafeObjectSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObjectSyncServer will
// result in compilation errors.
type UnsafeObjectSyncServer interface {
	mustEmbedUnimplementedObjectSyncServer()
}

func RegisterObjectSyncServer(s grpc.ServiceRegistrar, srv ObjectSyncServer) {
	s.RegisterService(&ObjectSync_ServiceDesc, srv)
}

func _ObjectSync_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ObjectSyncServer).Sync(&objectSyncSyncServer{stream})
}

type ObjectSync_SyncServer interface {
	Send(*ServerMsg) error
	Recv() (*ClientMsg, error)
	grpc.ServerStream
}

type objectSyncSyncServer struct {
	grpc.ServerStream
}

func (x *objectSyncSyncServer) Send(m *ServerMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *objectSyncSyncServer) Recv() (*ClientMsg, error) {
	m := new(ClientMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ObjectSync_ServiceDesc is the grpc.ServiceDesc for ObjectSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObjectSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "treevial.v1.ObjectSync",
	HandlerType: (*ObjectSyncServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _ObjectSync_Sync_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "treevial.proto",
}
