// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: treevial.proto

package treevialpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Body:
	//
	//	*ClientMsg_Register
	//	*ClientMsg_Ack
	Body isClientMsg_Body `protobuf_oneof:"body"`
}

func (x *ClientMsg) Reset() {
	*x = ClientMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_treevial_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMsg) ProtoMessage() {}

func (x *ClientMsg) ProtoReflect() protoreflect.Message {
	mi := &file_treevial_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMsg.ProtoReflect.Descriptor instead.
func (*ClientMsg) Descriptor() ([]byte, []int) {
	return file_treevial_proto_rawDescGZIP(), []int{0}
}

func (m *ClientMsg) GetBody() isClientMsg_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *ClientMsg) GetRegister() *Register {
	if x, ok := x.GetBody().(*ClientMsg_Register); ok {
		return x.Register
	}
	return nil
}

func (x *ClientMsg) GetAck() *Ack {
	if x, ok := x.GetBody().(*ClientMsg_Ack); ok {
		return x.Ack
	}
	return nil
}

type isClientMsg_Body interface {
	isClientMsg_Body()
}

type ClientMsg_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type ClientMsg_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*ClientMsg_Register) isClientMsg_Body() {}

func (*ClientMsg_Ack) isClientMsg_Body() {}

// Register opens the subscription. "synced" is the hash the client already
// holds in full, or empty if it holds nothing; the server sends the difference
// between it and the ref, and knows from it exactly where the client stands.
// The ref is not named here: it follows from the client ID in the header.
type Register struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Synced string `protobuf:"bytes,1,opt,name=synced,proto3" json:"synced,omitempty"`
}

func (x *Register) Reset() {
	*x = Register{}
	if protoimpl.UnsafeEnabled {
		mi := &file_treevial_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_treevial_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_treevial_proto_rawDescGZIP(), []int{1}
}

func (x *Register) GetSynced() string {
	if x != nil {
		return x.Synced
	}
	return ""
}

// Ack tells the server the client has fully interpreted an update and is now at
// "hash". Until it arrives, the server considers the client unsynced.
type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_treevial_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_treevial_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_treevial_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type ServerMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Body:
	//
	//	*ServerMsg_Begin
	//	*ServerMsg_Chunk
	//	*ServerMsg_End
	Body isServerMsg_Body `protobuf_oneof:"body"`
}

func (x *ServerMsg) Reset() {
	*x = ServerMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_treevial_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMsg) ProtoMessage() {}

func (x *ServerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_treevial_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMsg.ProtoReflect.Descriptor instead.
func (*ServerMsg) Descriptor() ([]byte, []int) {
	return file_treevial_proto_rawDescGZIP(), []int{3}
}

func (m *ServerMsg) GetBody() isServerMsg_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *ServerMsg) GetBegin() *UpdateBegin {
	if x, ok := x.GetBody().(*ServerMsg_Begin); ok {
		return x.Begin
	}
	return nil
}

func (x *ServerMsg) GetChunk() *PackChunk {
	if x, ok := x.GetBody().(*ServerMsg_Chunk); ok {
		return x.Chunk
	}
	return nil
}

func (x *ServerMsg) GetEnd() *UpdateEnd {
	if x, ok := x.GetBody().(*ServerMsg_End); ok {
		return x.End
	}
	return nil
}

type isServerMsg_Body interface {
	isServerMsg_Body()
}

type ServerMsg_Begin struct {
	Begin *UpdateBegin `protobuf:"bytes,1,opt,name=begin,proto3,oneof"`
}

type ServerMsg_Chunk struct {
	Chunk *PackChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

type ServerMsg_End struct {
	End *UpdateEnd `protobuf:"bytes,3,opt,name=end,proto3,oneof"`
}

func (*ServerMsg_Begin) isServerMsg_Body() {}

func (*ServerMsg_Chunk) isServerMsg_Body() {}

func (*ServerMsg_End) isServerMsg_Body() {}

// UpdateBegin opens an update. A count of zero means the client is already
// current and no pack follows.
type UpdateBegin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash        string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ObjectCount uint32 `protobuf:"varint,2,opt,name=object_count,json=objectCount,proto3" json:"object_count,omitempty"`
}

func (x *UpdateBegin) Reset() {
	*x = UpdateBegin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_treevial_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBegin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBegin) ProtoMessage() {}

func (x *UpdateBegin) ProtoReflect() protoreflect.Message {
	mi := &file_treevial_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBegin.ProtoReflect.Descriptor instead.
func (*UpdateBegin) Descriptor() ([]byte, []int) {
	return file_treevial_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBegin) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *UpdateBegin) GetObjectCount() uint32 {
	if x != nil {
		return x.ObjectCount
	}
	return 0
}

type PackChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PackChunk) Reset() {
	*x = PackChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_treevial_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackChunk) ProtoMessage() {}

func (x *PackChunk) ProtoReflect() protoreflect.Message {
	mi := &file_treevial_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackChunk.ProtoReflect.Descriptor instead.
func (*PackChunk) Descriptor() ([]byte, []int) {
	return file_treevial_proto_rawDescGZIP(), []int{5}
}

func (x *PackChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// UpdateEnd closes an update; the pack is complete and can be acknowledged.
type UpdateEnd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateEnd) Reset() {
	*x = UpdateEnd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_treevial_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnd) ProtoMessage() {}

func (x *UpdateEnd) ProtoReflect() protoreflect.Message {
	mi := &file_treevial_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnd.ProtoReflect.Descriptor instead.
func (*UpdateEnd) Descriptor() ([]byte, []int) {
	return file_treevial_proto_rawDescGZIP(), []int{6}
}

var File_treevial_proto protoreflect.FileDescriptor

var file_treevial_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x72, 0x65, 0x65, 0x76, 0x69, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x74, 0x72, 0x65, 0x65, 0x76, 0x69, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x22, 0x6e, 0x0a,
	0x09, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x33, 0x0a, 0x08, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74,
	0x72, 0x65, 0x65, 0x76, 0x69, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x24, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74,
	0x72, 0x65, 0x65, 0x76, 0x69, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x6b, 0x48, 0x00,
	0x52, 0x03, 0x61, 0x63, 0x6b, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x22, 0x0a,
	0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6e,
	0x63, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6e, 0x63, 0x65,
	0x64, 0x22, 0x19, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0xa1, 0x01, 0x0a,
	0x09, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x30, 0x0a, 0x05, 0x62, 0x65,
	0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x72, 0x65, 0x65,
	0x76, 0x69, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x65,
	0x67, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x05, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x2e, 0x0a, 0x05,
	0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x72,
	0x65, 0x65, 0x76, 0x69, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x48, 0x00, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x2a, 0x0a, 0x03,
	0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x72, 0x65, 0x65,
	0x76, 0x69, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e,
	0x64, 0x48, 0x00, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x22, 0x44, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x1f, 0x0a, 0x09, 0x50, 0x61, 0x63, 0x6b, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0b, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x45, 0x6e, 0x64, 0x32, 0x48, 0x0a, 0x0a, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x79,
	0x6e, 0x63, 0x12, 0x3a, 0x0a, 0x04, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x16, 0x2e, 0x74, 0x72, 0x65,
	0x65, 0x76, 0x69, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d,
	0x73, 0x67, 0x1a, 0x16, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x76, 0x69, 0x61, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x28, 0x01, 0x30, 0x01, 0x42, 0x3d,
	0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6f, 0x6c,
	0x6f, 0x70, 0x6c, 0x6f, 0x74, 0x2f, 0x74, 0x72, 0x65, 0x65, 0x76, 0x69, 0x61, 0x6c, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x72, 0x65, 0x65, 0x76, 0x69, 0x61, 0x6c,
	0x70, 0x62, 0x3b, 0x74, 0x72, 0x65, 0x65, 0x76, 0x69, 0x61, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_treevial_proto_rawDescOnce sync.Once
	file_treevial_proto_rawDescData = file_treevial_proto_rawDesc
)

func file_treevial_proto_rawDescGZIP() []byte {
	file_treevial_proto_rawDescOnce.Do(func() {
		file_treevial_proto_rawDescData = protoimpl.X.CompressGZIP(file_treevial_proto_rawDescData)
	})
	return file_treevial_proto_rawDescData
}

var file_treevial_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_treevial_proto_goTypes = []interface{}{
	(*ClientMsg)(nil),   // 0: treevial.v1.ClientMsg
	(*Register)(nil),    // 1: treevial.v1.Register
	(*Ack)(nil),         // 2: treevial.v1.Ack
	(*ServerMsg)(nil),   // 3: treevial.v1.ServerMsg
	(*UpdateBegin)(nil), // 4: treevial.v1.UpdateBegin
	(*PackChunk)(nil),   // 5: treevial.v1.PackChunk
	(*UpdateEnd)(nil),   // 6: treevial.v1.UpdateEnd
}
var file_treevial_proto_depIdxs = []int32{
	1, // 0: treevial.v1.ClientMsg.register:type_name -> treevial.v1.Register
	2, // 1: treevial.v1.ClientMsg.ack:type_name -> treevial.v1.Ack
	4, // 2: treevial.v1.ServerMsg.begin:type_name -> treevial.v1.UpdateBegin
	5, // 3: treevial.v1.ServerMsg.chunk:type_name -> treevial.v1.PackChunk
	6, // 4: treevial.v1.ServerMsg.end:type_name -> treevial.v1.UpdateEnd
	0, // 5: treevial.v1.ObjectSync.Sync:input_type -> treevial.v1.ClientMsg
	3, // 6: treevial.v1.ObjectSync.Sync:output_type -> treevial.v1.ServerMsg
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_treevial_proto_init() }
func file_treevial_proto_init() {
	if File_treevial_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_treevial_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_treevial_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Register); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_treevial_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_treevial_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_treevial_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBegin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_treevial_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_treevial_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEnd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_treevial_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ClientMsg_Register)(nil),
		(*ClientMsg_Ack)(nil),
	}
	file_treevial_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*ServerMsg_Begin)(nil),
		(*ServerMsg_Chunk)(nil),
		(*ServerMsg_End)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_treevial_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_treevial_proto_goTypes,
		DependencyIndexes: file_treevial_proto_depIdxs,
		MessageInfos:      file_treevial_proto_msgTypes,
	}.Build()
	File_treevial_proto = out.File
	file_treevial_proto_rawDesc = nil
	file_treevial_proto_goTypes = nil
	file_treevial_proto_depIdxs = nil
}
